# This goes in a file named either `.vale.ini` or `_vale.ini`.
StylesPath = styles
MinAlertLevel = suggestion

# External packages
Packages = Google, Readability, alex, proselint
# which type of files to check
[*.{md,txt,tex}]
# List of styles to load.
BasedOnStyles = alex, proselint
