#!/bin/bash
# Run this script to setup the config on a local machine

# Install Homebrew packages with sudo permissions
sudo -v
brew bundle --file Brewlite

# Setup hammmerspoon
curl -L https://github.com/Hammerspoon/Spoons/raw/master/Spoons/SpoonInstall.spoon.zip -o SpoonInstall.spoon.zip
# No idea if I need spoon install anymore
unzip SpoonInstall.spoon.zip -d .hammerspoon/Spoons
rm SpoonInstall.spoon.zip

# Link dotfiles to the home directory
stow .

# TODO: Rustup setup
# Install mise dependencies
# mise install # disabled for lite installation

# Could setup kanata in this step

# Restart shell instance
exec zsh
