tap "dart-lang/dart"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
tap "teamookla/speedtest"
brew "black"
brew "bottom"
brew "deno"
brew "fd"
brew "flake8"
brew "fzf"
brew "git"
brew "luajit", args: ["HEAD"]
brew "neofetch"
brew "neovim", args: ["HEAD"]
brew "node"
brew "nvm"
brew "pandoc"
brew "prettier"
brew "ripgrep"
brew "rustup-init", link: false
brew "stylua"
brew "swift"
brew "tmux"
brew "trash"
brew "vale"
brew "wget"
brew "yarn"
brew "dart-lang/dart/dart"
brew "romkatv/powerlevel10k/powerlevel10k"
brew "teamookla/speedtest/speedtest"
cask "basictex"
cask "kitty"
cask "wkhtmltopdf"
