tap "dart-lang/dart"
tap "gcenx/wine"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
brew "black"
brew "deno"
brew "fd"
brew "flake8"
brew "fzf"
brew "git"
brew "luajit", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "node"
brew "pandoc"
brew "prettier"
brew "ripgrep"
brew "rustup-init", link: false
brew "stylua"
brew "swift"
brew "tmux"
brew "trash"
brew "vale"
brew "wget"
brew "yarn"
brew "dart-lang/dart/dart"
brew "romkatv/powerlevel10k/powerlevel10k"
cask "basictex"
cask "unofficial-wineskin"
cask "wine-devel"
