# Reload tmux shortcut
bind-key -n M-C-S-r source-file ~/.config/tmux/tmux.conf \; display-message "tmux configuration reloaded"
source ~/.config/tmux/tmux-options.conf
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins"
set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'jaclu/tmux-power-zoom'
set -g @plugin 'tmux-plugins/tmux-resurrect' # restore tmux sessions
set -g @resurrect-capture-pane-contents 'on'
# set -g @resurrect-strategy-nvim 'session' # restore nvim session (requires vim-obsession)
set -g @resurrect-dir '~/.config/tmux/plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-boot-options 'kitty,fullscreen'
source ~/.config/tmux/tmux-status.conf
source ~/.config/tmux/tmux-navigation.conf
source ~/.config/tmux/tmux-smart-splits.conf
source ~/.config/tmux/tmux-sesh.conf

# initialise tpm (keep at end of file)
if "test ! -d $TMUX_PLUGIN_MANAGER_PATH/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm $TMUX_PLUGIN_MANAGER_PATH/tpm && $TMUX_PLUGIN_MANAGER_PATH/tpm/bin/install_plugins'"
run "~/.config/tmux/plugins/tpm/tpm"
