set -g default-terminal "${TERM}" # xterm-kitty
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0
bind-key C-b send-prefix # for when using tmux through ssh I think
set -g escape-time 0 # pressing escape is instant
set -g history-limit 5000 # more scrollback
set -g display-time 2000 # messages displayed longer
set -g status-keys emacs # better typing in status
setw -g mode-keys vi # vim mode bindings for copy mode
set -g mouse on # enable mouse for tmux
set -g status-interval 60 # status refreshes less often
setw -g aggressive-resize on
set-option -g detach-on-destroy off # don't detach from current instance when killing session
setw -g monitor-activity on
set -g visual-activity off
set-option -g bell-action none
set -s exit-empty off # stop tmux detaching
set -g focus-events on # vim can detect focus gained and lost
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -as terminal-features ",*:hyperlinks" # enable hyperlinks
