unbind '"'; unbind "%" # unbind old commands
# Window and pane commands
bind -n M-o last-window # go to last window
bind -n M-c new-window -c "#{pane_current_path}" # window opens in cwd
bind -n M-- split-window -v -c "#{pane_current_path}" # horizontal pane
bind -n M-_ split-window -fv -c "#{pane_current_path}" # horizontal pane
bind -n M-\\ split-window -h -c "#{pane_current_path}" # vertical pane
bind -n M-| split-window -fh -c "#{pane_current_path}" # vertical pane
bind -n M-x kill-pane
bind -n M-C-x kill-session

# Window navigation
bind -rn C-S-Tab previous-window
bind -rn C-Tab next-window

# Switch to window with number
bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Tmux layout toggling
bind -rn M-= next-layout

# Reorder windows
bind -rn M-, swap-window -d -t -1
bind -rn M-. swap-window -d -t +1

bind -n M-e set-window-option synchronize-panes # sync panes with command

# Open session and window trees
bind -n M-s choose-session
bind -n M-w choose-window

bind -n M-C-s switch-client -l
bind -n M-C-p switch-client -p
bind -n M-C-n switch-client -n

bind -n M-C-c command-prompt "new-session -s '%%'"
bind -n M-C-r command-prompt "rename-session '%%'"
bind -n M-r command-prompt "rename-window '%%'"
