-- -- debug adaptor protocol
-- -- one day I'll work more on lazy loading eveything
-- { "mfussenegger/nvim-dap", lazy = true,
--   config = req("john.dap"),
--   dependencies = {
--     -- issue with lazy loading this plugin causes bufferline.nvim and gitsigns.nvim to create insert mode bugs while using telescope to launch a file from an emtpy buffer
--     { "rcarriga/nvim-dap-ui",              config = setup("dapui"), },
--     { "theHamsta/nvim-dap-virtual-text",   config = setup("nvim-dap-virtual-text"), },
--     { "jbyuki/one-small-step-for-vimkind", ft = "lua" },
--   },
-- },
