'$schema' = 'https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json'

[general]
allow_concurrent_presets = false

[defaults]
kanata_executable = '~/.config/cargo/bin/kanata' # if empty or omitted, system $PATH will be searched.
kanata_config = '~/.config/kanata/kanata.kbd'    # if empty or not omitted, kanata default config locations will be used.
tcp_port = 5829                                  # if not specified, defaults to 5829

[defaults.hooks]
post-start-async = ["zsh -c ~/.config/kanata/run.sh"]
# Hooks allow running custom commands on specific events (e.g. starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[presets.'main cfg']
autorun = true
kanata_config = '~/.config/kanata/main.kbd'

[presets.'gaming cfg']
kanata_config = '~/.config/kanata/gaming.kbd'
