[user]
name = "Henry Wang"
email = "wang.henryhan@gmail.com"

[ui]
default-command = "st"

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | remote_bookmarks()"

[git]
private-commits = '''description(glob:'private:*')'''
