[tools]
node = { version = "latest", postinstall = "corepack enable" }
java = "21"
pipx = "latest"
go = "latest"

# productivity
"ubi:jtroo/kanata" = "latest"

# apps
"ubi:Cretezy/lazyjj" = "latest"

# tools
cargo-binstall = "latest"
"npm:epub-wordcount" = "latest"
"cargo:av1an" = "latest"
"cargo:hayagriva" = "latest"

# cargo helpers
"cargo:cargo-generate" = "latest"
"cargo:cargo-clean-recursive" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-wizard" = "latest"
"cargo:cargo-info" = "latest"

# tauri
"cargo:tauri-cli" = "latest"
"cargo:create-tauri-app" = "latest"

# wasm
"cargo:wasm-bindgen-cli" = "latest"
"cargo:twiggy" = "latest"
"ubi:bram209/leptosfmt" = "latest"
"cargo:perseus-cli" = "latest"
"cargo:stylance-cli" = "latest"
"cargo:trunk" = "latest"
usage = "latest"
"ubi:leptos-rs/cargo-leptos" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
