[tools]
node = "latest"
java = "21"
pipx = "latest"
go = "latest"

# installed cargo programs
"cargo:cargo-binstall" = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-clean-recursive" = "latest"
"cargo:create-tauri-app" = "latest"
"cargo:hayagriva" = "latest"
"cargo:kanata" = "latest"
"cargo:leptosfmt" = "latest"
"cargo:perseus-cli" = "latest"
"cargo:stylance-cli" = "latest"
"cargo:tauri-cli" = "latest"
"cargo:trunk" = "latest"
"cargo:typstfmt" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:av1an" = "latest"
"cargo:cargo-wizard" = "latest"
"cargo:cargo-bloat" = "latest"
"cargo:twiggy" = "latest"
"cargo:cargo-info" = "latest"
"cargo:lazyjj" = "latest"

"npm:epub-wordcount" = "latest"
"cargo:wasm-bindgen-cli" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
